---
# Création d'un namespace dedié
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-demo-hpa

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  labels:
    app: frontend-hpa
  namespace: kubernetes-demo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-hpa
  minReplicas: 3
  maxReplicas: 30
  targetCPUUtilizationPercentage: 10

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-hpa
  namespace: kubernetes-demo-hpa
  labels:
    projet: tp_deploy
    type: deploy-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-hpa
  template:
    metadata:
      labels:
        app: frontend-hpa
    spec:
      containers:
      - name: frontend
        image: bilbloke/frontend:1.0
        ports:
        - containerPort: 80
        resources:
            requests:
              cpu: 10m
            limits:
              memory: "128Mi"
              cpu: "10m"

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-hpa
  namespace: kubernetes-demo-hpa
  labels:
    app: frontend-hpa
    projet: tp_deploy
spec:
  selector:
    app: frontend-hpa
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001