apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    projet: tp_deploy
    type: deploy-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        kubernetes.io/change-cause: "Mise à jour couleur code php avec image version bilbloke"
    spec:
      containers:
      - name: frontend
        image: bilbloke/frontend:2.0
        ports:
        - containerPort: 80