apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap-web
spec:
  containers:
    - name: www
      image: nginx:1.18-alpine
      volumeMounts:
      - name: nginx-volume-web
        mountPath: /usr/share/nginx/html/
  volumes:
  - name: nginx-volume-web
    configMap:
      name: demo-configmap-web
      items:
        - key: code
          path: index.html
